# Gems
gems:
  - jekyll-gist
# Dependencies
markdown:         kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            U2-I2
tagline:          'U2I2'
description:      'An one-stop solution to explore user unresettable identifiers (UUIs) leakage on your Android smartphone.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://github.com/trustlab

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cyberooo/u2i2
